zuul:
  routes:
    abelibrary:
      url: http://localhost:8084
    abecreditcard:
      url: http://localhost:8083
    abeaudit:
      url: http://localhost:8082
    amazon-authy:
      url: http://localhost:9001
server:
  port:
    8080